### PR TITLE
Upgraded Go CI from 1.16 to 1.17.7

### LINKED ISSUE #146: Upgrade GitHub actions CI to use latest Golang binaries
Currently the CI is using `Go 1.16`, it'll be great to move to `Go 1.17.7` for [smaller binary sizes, faster runtimes, ](https://go.dev/blog/go1.17).

# Steps

1. Become familiar with GitHub Actions
2. See how this project uses Golang GitHub actions
3. Bump up the `1.16` to `1.17.7`
4. Evaluate if anything else needs to be bumped up & if there's a GitHub action for the same & let us know about it in comments.

### PR DESCRIPTION
**Pull request by MukulKolpe**
Signed-off-by: Mukul Kolpe <mukulkolpe45@gmail.com>

Fixes #146

### CODE REVIEW

**Review by vharsh — APPROVED** [review]
lgtm, thanks for your first contribution to openebsctl @MukulKolpe 🎉🎈

**Comment by MukulKolpe** [comment]
Thank you @vharsh for helping😀

**Comment by vharsh** [comment]
Sure let me know if you'd like to take up more issues, btw, we hang out in #openebs-dev & #openebs on slack.k8s.io 🥂 💯

**Comment by MukulKolpe** [comment]
Yes @vharsh, I would like to take up more issues. Please let me know if there are more issues to work on. I've joined slack channels✅.

**Pull request merged**
